/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ACaseCaseSequence extends PCaseSequence
{
    private PCase _case_;

    public ACaseCaseSequence()
    {
        // Constructor
    }

    public ACaseCaseSequence(
        @SuppressWarnings("hiding") PCase _case_)
    {
        // Constructor
        setCase(_case_);

    }

    @Override
    public Object clone()
    {
        return new ACaseCaseSequence(
            cloneNode(this._case_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaseCaseSequence(this);
    }

    public PCase getCase()
    {
        return this._case_;
    }

    public void setCase(PCase node)
    {
        if(this._case_ != null)
        {
            this._case_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._case_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._case_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._case_ == child)
        {
            this._case_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._case_ == oldChild)
        {
            setCase((PCase) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
