/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ADclSequenceDeclSequence extends PDeclSequence
{
    private PDeclSequence _declSequence_;
    private PDeclaracao _declaracao_;

    public ADclSequenceDeclSequence()
    {
        // Constructor
    }

    public ADclSequenceDeclSequence(
        @SuppressWarnings("hiding") PDeclSequence _declSequence_,
        @SuppressWarnings("hiding") PDeclaracao _declaracao_)
    {
        // Constructor
        setDeclSequence(_declSequence_);

        setDeclaracao(_declaracao_);

    }

    @Override
    public Object clone()
    {
        return new ADclSequenceDeclSequence(
            cloneNode(this._declSequence_),
            cloneNode(this._declaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADclSequenceDeclSequence(this);
    }

    public PDeclSequence getDeclSequence()
    {
        return this._declSequence_;
    }

    public void setDeclSequence(PDeclSequence node)
    {
        if(this._declSequence_ != null)
        {
            this._declSequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declSequence_ = node;
    }

    public PDeclaracao getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(PDeclaracao node)
    {
        if(this._declaracao_ != null)
        {
            this._declaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declSequence_)
            + toString(this._declaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declSequence_ == child)
        {
            this._declSequence_ = null;
            return;
        }

        if(this._declaracao_ == child)
        {
            this._declaracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declSequence_ == oldChild)
        {
            setDeclSequence((PDeclSequence) newChild);
            return;
        }

        if(this._declaracao_ == oldChild)
        {
            setDeclaracao((PDeclaracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
