/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AElem5Elemento1 extends PElemento1
{
    private PTermo5 _termo5_;

    public AElem5Elemento1()
    {
        // Constructor
    }

    public AElem5Elemento1(
        @SuppressWarnings("hiding") PTermo5 _termo5_)
    {
        // Constructor
        setTermo5(_termo5_);

    }

    @Override
    public Object clone()
    {
        return new AElem5Elemento1(
            cloneNode(this._termo5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElem5Elemento1(this);
    }

    public PTermo5 getTermo5()
    {
        return this._termo5_;
    }

    public void setTermo5(PTermo5 node)
    {
        if(this._termo5_ != null)
        {
            this._termo5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo5_ == child)
        {
            this._termo5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo5_ == oldChild)
        {
            setTermo5((PTermo5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
