/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AETermo2 extends PTermo2
{
    private PTermo2 _termo2_;
    private TE _e_;
    private PElemento1 _elemento1_;

    public AETermo2()
    {
        // Constructor
    }

    public AETermo2(
        @SuppressWarnings("hiding") PTermo2 _termo2_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PElemento1 _elemento1_)
    {
        // Constructor
        setTermo2(_termo2_);

        setE(_e_);

        setElemento1(_elemento1_);

    }

    @Override
    public Object clone()
    {
        return new AETermo2(
            cloneNode(this._termo2_),
            cloneNode(this._e_),
            cloneNode(this._elemento1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAETermo2(this);
    }

    public PTermo2 getTermo2()
    {
        return this._termo2_;
    }

    public void setTermo2(PTermo2 node)
    {
        if(this._termo2_ != null)
        {
            this._termo2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo2_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PElemento1 getElemento1()
    {
        return this._elemento1_;
    }

    public void setElemento1(PElemento1 node)
    {
        if(this._elemento1_ != null)
        {
            this._elemento1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elemento1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo2_)
            + toString(this._e_)
            + toString(this._elemento1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo2_ == child)
        {
            this._termo2_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._elemento1_ == child)
        {
            this._elemento1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo2_ == oldChild)
        {
            setTermo2((PTermo2) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._elemento1_ == oldChild)
        {
            setElemento1((PElemento1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
