/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMaiorOpComp extends POpComp
{
    private TMaiorQue _maiorQue_;

    public AMaiorOpComp()
    {
        // Constructor
    }

    public AMaiorOpComp(
        @SuppressWarnings("hiding") TMaiorQue _maiorQue_)
    {
        // Constructor
        setMaiorQue(_maiorQue_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorOpComp(
            cloneNode(this._maiorQue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorOpComp(this);
    }

    public TMaiorQue getMaiorQue()
    {
        return this._maiorQue_;
    }

    public void setMaiorQue(TMaiorQue node)
    {
        if(this._maiorQue_ != null)
        {
            this._maiorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._maiorQue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._maiorQue_ == child)
        {
            this._maiorQue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._maiorQue_ == oldChild)
        {
            setMaiorQue((TMaiorQue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
