/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpIgualTermo3 extends PTermo3
{
    private PTermo7 _termo7_;
    private POpIgualdade _opIgualdade_;
    private PTermo7Aux _termo7Aux_;

    public AOpIgualTermo3()
    {
        // Constructor
    }

    public AOpIgualTermo3(
        @SuppressWarnings("hiding") PTermo7 _termo7_,
        @SuppressWarnings("hiding") POpIgualdade _opIgualdade_,
        @SuppressWarnings("hiding") PTermo7Aux _termo7Aux_)
    {
        // Constructor
        setTermo7(_termo7_);

        setOpIgualdade(_opIgualdade_);

        setTermo7Aux(_termo7Aux_);

    }

    @Override
    public Object clone()
    {
        return new AOpIgualTermo3(
            cloneNode(this._termo7_),
            cloneNode(this._opIgualdade_),
            cloneNode(this._termo7Aux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpIgualTermo3(this);
    }

    public PTermo7 getTermo7()
    {
        return this._termo7_;
    }

    public void setTermo7(PTermo7 node)
    {
        if(this._termo7_ != null)
        {
            this._termo7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo7_ = node;
    }

    public POpIgualdade getOpIgualdade()
    {
        return this._opIgualdade_;
    }

    public void setOpIgualdade(POpIgualdade node)
    {
        if(this._opIgualdade_ != null)
        {
            this._opIgualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opIgualdade_ = node;
    }

    public PTermo7Aux getTermo7Aux()
    {
        return this._termo7Aux_;
    }

    public void setTermo7Aux(PTermo7Aux node)
    {
        if(this._termo7Aux_ != null)
        {
            this._termo7Aux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo7Aux_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo7_)
            + toString(this._opIgualdade_)
            + toString(this._termo7Aux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo7_ == child)
        {
            this._termo7_ = null;
            return;
        }

        if(this._opIgualdade_ == child)
        {
            this._opIgualdade_ = null;
            return;
        }

        if(this._termo7Aux_ == child)
        {
            this._termo7Aux_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo7_ == oldChild)
        {
            setTermo7((PTermo7) newChild);
            return;
        }

        if(this._opIgualdade_ == oldChild)
        {
            setOpIgualdade((POpIgualdade) newChild);
            return;
        }

        if(this._termo7Aux_ == oldChild)
        {
            setTermo7Aux((PTermo7Aux) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
