/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpMultTermo extends PTermo
{
    private PTermo _termo_;
    private POpMult _opMult_;
    private PFator _fator_;

    public AOpMultTermo()
    {
        // Constructor
    }

    public AOpMultTermo(
        @SuppressWarnings("hiding") PTermo _termo_,
        @SuppressWarnings("hiding") POpMult _opMult_,
        @SuppressWarnings("hiding") PFator _fator_)
    {
        // Constructor
        setTermo(_termo_);

        setOpMult(_opMult_);

        setFator(_fator_);

    }

    @Override
    public Object clone()
    {
        return new AOpMultTermo(
            cloneNode(this._termo_),
            cloneNode(this._opMult_),
            cloneNode(this._fator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpMultTermo(this);
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    public POpMult getOpMult()
    {
        return this._opMult_;
    }

    public void setOpMult(POpMult node)
    {
        if(this._opMult_ != null)
        {
            this._opMult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opMult_ = node;
    }

    public PFator getFator()
    {
        return this._fator_;
    }

    public void setFator(PFator node)
    {
        if(this._fator_ != null)
        {
            this._fator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo_)
            + toString(this._opMult_)
            + toString(this._fator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        if(this._opMult_ == child)
        {
            this._opMult_ = null;
            return;
        }

        if(this._fator_ == child)
        {
            this._fator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        if(this._opMult_ == oldChild)
        {
            setOpMult((POpMult) newChild);
            return;
        }

        if(this._fator_ == oldChild)
        {
            setFator((PFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
