/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpSumExpAux extends PExpAux
{
    private PExpAux _expAux_;
    private POpSum _opSum_;
    private PTermoAux _termoAux_;

    public AOpSumExpAux()
    {
        // Constructor
    }

    public AOpSumExpAux(
        @SuppressWarnings("hiding") PExpAux _expAux_,
        @SuppressWarnings("hiding") POpSum _opSum_,
        @SuppressWarnings("hiding") PTermoAux _termoAux_)
    {
        // Constructor
        setExpAux(_expAux_);

        setOpSum(_opSum_);

        setTermoAux(_termoAux_);

    }

    @Override
    public Object clone()
    {
        return new AOpSumExpAux(
            cloneNode(this._expAux_),
            cloneNode(this._opSum_),
            cloneNode(this._termoAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpSumExpAux(this);
    }

    public PExpAux getExpAux()
    {
        return this._expAux_;
    }

    public void setExpAux(PExpAux node)
    {
        if(this._expAux_ != null)
        {
            this._expAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAux_ = node;
    }

    public POpSum getOpSum()
    {
        return this._opSum_;
    }

    public void setOpSum(POpSum node)
    {
        if(this._opSum_ != null)
        {
            this._opSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opSum_ = node;
    }

    public PTermoAux getTermoAux()
    {
        return this._termoAux_;
    }

    public void setTermoAux(PTermoAux node)
    {
        if(this._termoAux_ != null)
        {
            this._termoAux_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAux_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAux_)
            + toString(this._opSum_)
            + toString(this._termoAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAux_ == child)
        {
            this._expAux_ = null;
            return;
        }

        if(this._opSum_ == child)
        {
            this._opSum_ = null;
            return;
        }

        if(this._termoAux_ == child)
        {
            this._termoAux_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAux_ == oldChild)
        {
            setExpAux((PExpAux) newChild);
            return;
        }

        if(this._opSum_ == oldChild)
        {
            setOpSum((POpSum) newChild);
            return;
        }

        if(this._termoAux_ == oldChild)
        {
            setTermoAux((PTermoAux) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
