/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpSumExp extends PExp
{
    private PExp _exp_;
    private POpSum _opSum_;
    private PTermo _termo_;

    public AOpSumExp()
    {
        // Constructor
    }

    public AOpSumExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") POpSum _opSum_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setExp(_exp_);

        setOpSum(_opSum_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new AOpSumExp(
            cloneNode(this._exp_),
            cloneNode(this._opSum_),
            cloneNode(this._termo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpSumExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public POpSum getOpSum()
    {
        return this._opSum_;
    }

    public void setOpSum(POpSum node)
    {
        if(this._opSum_ != null)
        {
            this._opSum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opSum_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._opSum_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._opSum_ == child)
        {
            this._opSum_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._opSum_ == oldChild)
        {
            setOpSum((POpSum) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
