/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ATermo1ExpLogica extends PExpLogica
{
    private PTermo1 _termo1_;

    public ATermo1ExpLogica()
    {
        // Constructor
    }

    public ATermo1ExpLogica(
        @SuppressWarnings("hiding") PTermo1 _termo1_)
    {
        // Constructor
        setTermo1(_termo1_);

    }

    @Override
    public Object clone()
    {
        return new ATermo1ExpLogica(
            cloneNode(this._termo1_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermo1ExpLogica(this);
    }

    public PTermo1 getTermo1()
    {
        return this._termo1_;
    }

    public void setTermo1(PTermo1 node)
    {
        if(this._termo1_ != null)
        {
            this._termo1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo1_ == child)
        {
            this._termo1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo1_ == oldChild)
        {
            setTermo1((PTermo1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
