/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AVarSequenceVarSequence extends PVarSequence
{
    private PVarSequence _varSequence_;
    private TVirgula _virgula_;
    private PVar _var_;

    public AVarSequenceVarSequence()
    {
        // Constructor
    }

    public AVarSequenceVarSequence(
        @SuppressWarnings("hiding") PVarSequence _varSequence_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PVar _var_)
    {
        // Constructor
        setVarSequence(_varSequence_);

        setVirgula(_virgula_);

        setVar(_var_);

    }

    @Override
    public Object clone()
    {
        return new AVarSequenceVarSequence(
            cloneNode(this._varSequence_),
            cloneNode(this._virgula_),
            cloneNode(this._var_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarSequenceVarSequence(this);
    }

    public PVarSequence getVarSequence()
    {
        return this._varSequence_;
    }

    public void setVarSequence(PVarSequence node)
    {
        if(this._varSequence_ != null)
        {
            this._varSequence_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varSequence_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varSequence_)
            + toString(this._virgula_)
            + toString(this._var_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varSequence_ == child)
        {
            this._varSequence_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varSequence_ == oldChild)
        {
            setVarSequence((PVarSequence) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
