/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TFimSe extends Token
{
    public TFimSe()
    {
        super.setText("fim se");
    }

    public TFimSe(int line, int pos)
    {
        super.setText("fim se");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimSe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimSe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimSe text.");
    }
}
